import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClickSparkles from "@/components/ClickSparkles";
import Preloader from "@/components/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-kh-teka antialiased"
      >
        {/* Preloader overlay */}
        {/* Note: server renders it visible; it unmounts itself after 3s + reveal */}
        {/* @ts-expect-error Server Component importing client child */}
        <Preloader />
        {children}
        <ClickSparkles />
      </body>
    </html>
  );
}
